### ISSUE TITLE
Invalid occurrences for "every 2 months on the last Monday"

### ISSUE THREAD

**Issue by tomquist** [fmeringdal/rust-rrule#104]
The following test fails:
```
#[test]
fn issue_YY() {
    let dates = "DTSTART;TZID=Europe/London:20231030T140000
RRULE:FREQ=MONTHLY;INTERVAL=2;BYDAY=-1MO"
        .parse::<RRuleSet>()
        .unwrap()
        .all(3)
        .dates;

        common::check_occurrences(
            &dates,
            &[
                "2023-10-30T14:00:00+00:00",
                "2023-12-25T14:00:00+00:00",
                "2024-02-26T14:00:00+00:00",
            ],
        );
}
```
This is the output:
```
Given: [
    "2023-10-30T14:00:00+00:00",
    "2023-12-25T14:00:00+00:00",
    "2024-03-25T14:00:00+00:00",
]
Expected: [
    "2023-10-30T14:00:00+00:00",
    "2023-12-25T14:00:00+00:00",
    "2024-02-26T14:00:00+00:00",
]
```

It seems all occurrences after crossing the year 2023/2024 are wrong.

**Comment by fmeringdal** [comment]
@tomquist Really busy these days so wont be able to provide much guidance the next couple of weeks. Any help on fixing this is appreciated.  My initial suspicion is that something is off in [RRuleIter::generate](https://github.com/fmeringdal/rust-rrule/blob/main/rrule/src/iter/rrule_iter.rs#L85). Also thank you for reporting this issue!

**Comment by sciyoshi** [comment]
Submitted a fix here https://github.com/fmeringdal/rust-rrule/pull/106 which resolves this issue although I'm not 100% sure it's fully correct.
