### ISSUE TITLE
Fail fast on invalid rrule configuration

### ISSUE THREAD

**Issue by fmeringdal** [fmeringdal/rust-rrule#23]
There are certain rrule configurations that are invalid. Some examples:
- Invalid timezone identifiers
- `bysetpos` is defined but no other by* rule was defined
- ...

It is important that `RRule` (and `ParsedOptions`) never can be created with such invalid configurations.  Any operations that try to build a `ParsedOptions` from an invalid configuration needs to return an error, which is not the case atm.

**Comment by ralpha** [comment]
Massive improvements made in #28
More might be added later, but I think this can be closed now.
