### ISSUE TITLE
Removing by_easter filter

### ISSUE THREAD

**Issue by ralpha** [fmeringdal/rust-rrule#26]
In the current implementation has special code for `BYEASTER`.
This is however not part of the RFC, but is a left over from the python implementation.

Do we want to keep supporting this?
This code is [practically unmaintainable right now](https://github.com/fmeringdal/rust-rrule/blob/2b93e7edafd9b64a8cfc5e29b2c69d420875a64f/src/iter/easter.rs) nor very useful I think.
It could be used to calculate other events like Good Friday, Whit Monday, ...

I'm in favor of removing this and in turn making the other parts of the code easier the maintain.
But I'm curious what other peoples opinion is.

**Comment by fmeringdal** [comment]
I think it is ok to remove it for now as it is unmaintainable. 
However, I do think it is a useful feature and should be added later (with maintable code).

**Comment by ralpha** [comment]
I was able to isolate it for now. So I put it under a feature flag. So people can opt-in to it. Also with some improve validation I was able to make is much more stable even at its current implementation.

The code should still be improved, but at least it can not be used to crash it.

**Comment by ralpha** [comment]
Under feature flag since #28
