### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by ralpha** [fmeringdal/rust-rrule#27]
I'm proposing to change the license from the current MIT license to a dual license MIT and Apache License v2.

This is just because almost all Rust crates (and [Rust itself](https://www.rust-lang.org/policies/licenses)) use these licenses and thus will make things more uniform.
This is a minor change and will not effect the project much, but just makes it more convenient.

@fmeringdal if you agree I'll update this in my fork and will be changed once everything is merged.

**Comment by fmeringdal** [comment]
Good idea. Go ahead @ralpha :)
