### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by ralpha** [fmeringdal/rust-rrule#30]
This issues was created because TODO items where removed from readme page.

@fmeringdal could you please clarify what exactly needs to be added and where this would fit in.

**Comment by omid** [comment]
So if there is no description @fmeringdal, maybe we can close it until it came back again.

**Comment by fmeringdal** [comment]
Yes, it can be closed as there is no clear description of how this caching should work. If someone comes later and asks for caching we can consider implementing it.
