### ISSUE TITLE
Fix `second_to_last_weekday_of_month` test

### ISSUE THREAD

**Issue by ralpha** [fmeringdal/rust-rrule#34]
The rrule 
```
DTSTART;TZID=America/New_York:19970929T090000
RRULE:FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-2
```
is incorrectly validated or/and produces incorrect results.

Expected:
```
"1997-09-29T09:00:00-05:00",
"1997-10-30T09:00:00-05:00",
"1997-11-27T09:00:00-05:00",
"1997-12-30T09:00:00-05:00",
"1998-01-29T09:00:00-05:00",
"1998-02-26T09:00:00-05:00",
"1998-03-30T09:00:00-05:00",
```

Current result (incorrect):
```
"1997-10-29T09:00:00-05:00",
"1997-11-26T09:00:00-05:00",
"1997-12-29T09:00:00-05:00",
"1998-01-28T09:00:00-05:00",
"1998-02-25T09:00:00-05:00",
"1998-03-29T09:00:00-05:00",
"1998-04-28T09:00:00-04:00",
```

See test: `second_to_last_weekday_of_month`
Test source: https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html

**Comment by fmeringdal** [comment]
I started digging in a little bit now and found that changing [this line](https://github.com/fmeringdal/rust-rrule/blob/main/rrule/src/iter/pos_list.rs#L58) from:
`from_ordinal(ii.year_ordinal().unwrap() + i as i64, tz);` to `from_ordinal(ii.year_ordinal().unwrap() + i as i64, &UTC);` produces the correct values except that it does not produce the first occurrence if it is equal to `DTSTART`.

The same thing happens with #33 so I think they are the same bug and one of them can be closed.
