### ISSUE TITLE
no-validation-limits vs validation-limits

### ISSUE THREAD

**Issue by omid** [fmeringdal/rust-rrule#38]
I suggest having `validation-limits` instead of `no-validation-limits`.
`validation-limits` should be enabled by `default`.

As you can in the following link: `As a related note, Cargo requires that features are additive so a feature named negatively like no-abc is practically never correct.`

https://rust-lang.github.io/api-guidelines/naming.html#c-feature

**Comment by ralpha** [comment]
This feature sounds more like a setting then a feature flag. So maybe we have to create some settings or different functions you call when you want the non-limited version. Like a `all_between_no_limited`, `all_between_unchecked`, `all_between_unvalidated` or ...

**Comment by omid** [comment]
I agree 👍🏼 
Some other naming ideas, `some_between` for limited vs `all_between` for no limit
