### ISSUE TITLE
Add optional Serde support

### ISSUE THREAD

**Issue by ralpha** [fmeringdal/rust-rrule#40]
Add Serde support for various structs. (`RRuleProperties`, `NWeekday`, `Frequency`, ...)

For more info see: #21

**Comment by fmeringdal** [comment]
Questions we should answer before starting the implementation:
- Should we implement serde for `RRule`?
- What type should  `RRuleProperties` deserialize from? String with a custom serde implementation or JSON with the default serde derive implementation. 
- Anything else?
