### ISSUE TITLE
ExRule limit feature

### ISSUE THREAD

**Issue by ralpha** [fmeringdal/rust-rrule#47]
I think we should put `ExDate` behind a feature flag or setting. As this is not part of the [RFC 5545](https://icalendar.org/iCalendar-RFC-5545/3-3-10-recurrence-rule.html) but but only part of the preceding [RFC 2445](https://datatracker.ietf.org/doc/html/rfc2445) spec.

**Comment by omid** [comment]
@ralpha in the description you said `ExDate`. But I think you meant `EXRULE`, no?
