### ISSUE TITLE
"Invalid by_month value" error message on RRULE definition

### ISSUE THREAD

**Issue by aggregat4** [fmeringdal/rust-rrule#48]
If I feed the following definition to rrule then I get an `Invalid by_month value` error from rrule:

```
"DTSTART;VALUE=DATE:20211206\nRRULE:FREQ=YEARLY;UNTIL=20211205T230000Z;INTERVAL=1;BYMONTHDAY=6;BYMONTH=12".parse::<RRuleSet>().unwrap()
```

The same definition but with a BYMONTH=11 works.

**Comment by fmeringdal** [comment]
Thanks for reporting this issue. It should be fixed in `v0.7.1`.
Feel free to reopen if the issue persist.
