### ISSUE TITLE
Returning `(Vec<DateTime>, bool)` is a bad practice

### ISSUE THREAD

**Issue by omid** [fmeringdal/rust-rrule#80]
It's unknown what are the meaning of the elements in the `(Vec<DateTime>, bool)` tuple in the response of `all` method and some others.

Better to return a struct with proper naming and methods.

**Comment by fmeringdal** [comment]
Well, I wouldn't say it is bad practice to return a tuple :) I think it is quite concise and the method has documentation that explains the meaning. It is not so important for me if the method returns a struct or a tuple, but feel free to open an MR for returning a struct and I will gladly merge it

**Comment by omid** [comment]
Just imagine a world in which there were no Result and Option, but just tuples :D

**Comment by fmeringdal** [comment]
Hehe, I didn't say I think tuples should completely replace everything :D I see your point of wanting to return a struct tho
